import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

i18n
  .use(LanguageDetector)
  .init({
    // we init with resources
    resources: {
      en: {
        translations: {
          "the_value": "THE VALUE",
          "partners": "PARTNERS",
          "the_game": "THE GAME",
          "token_sale": "TOKEN SALE",
          "roadmap": "ROADMAP",
          "team": "TEAM",
          "contact": "CONTACT",
          "game": "Game",
          "token": "Token",
          "crypto_game_rewards": "Crypto Game Rewards Powered by Real Honey Farms",
          "play_and_earn": "Play and earn game rewards with real world value!",
          "read_whitepaper": "Read white paper",
          "a_unique_bus": "A unique business model",
          "for_game_rewards": "for game rewards",
          "btny_built_off": "Bitney is built off an established, revenue generating honey business. Profits from honey sales are used to purchase Bitney tokens from exchanges. From this buyback, 20% of the tokens are burned, and 80% is redeposited into the Beeznix Game Rewards Bank. This cycle safeguards Bitney’s value.",
          "coming_soon": "Coming Soon",
          "game_trailer": "Game Trailer",
          "more_honey": "MORE HONEY, MORE MONEY",
          "corss_industry": "A CROSS-INDUSTRY COOPERATIVE VENTURE USING A MOBILE GAME TO ACCELERATE SCALING UP OF SMALL TO MEDIUM HONEY FARMS AROUND THE WORLD.",
          "bithubs_interactive": "Bitbubs Interactive teams up with Bee Republic, a honey farmers’ initiative, creating an unique ecosystem where revenue from a mobile gameverse funds the expansion of honey farms, and vice versa as the two businesses expand at an accelerated rate.",
          "out_partners": "OUR PARTNERS",
          "beeznix_heists": "BEEZNIX: THE HONEY HEISTS GAME",
          "a_massively_multi": 'A Massively Multiplayer Platform Action/Strategy with Base Builder, using ERC721 non-fungible tokens (NFTs) as "blueprints" to create an intelligence economy, allowing players to monetize their game assets with true ownership.',
          "based_on_a_story": "Based on a story of an 8-year old orphan who works in a toy bear sweatshop, this colorful game brings to life his brilliant imaginary world, a coping mechanism born from his despair. A parallel universe is created, based on the child’s greatest loves and fears, and objects in his daily life are translated into a “Honeyverse” where the following elements bring great playability and real rewards:",
          "build_your_base": "Build your base to protect your hives",
          "collect_character_blueprints": "Collect character blueprints to spawn units",
          "visit_other_players": "Visit other players' bases to steal their honey",
          "sell_your_honey": "Sell your honey for Bitney",
          "sell_your_blueprints": "Sell your blueprints for Bitney",
          "creating_an_intell": "CREATING AN INTELLIGENCE ECONOMY",
          "the_bluepz_concept": "The Bluepz (ERC721 blueprints) concept opens up a new dimension in gaming by allowing players to monetize their in-game ‘intellectual property’. Compared to skins, bluepz are considered knowledge or intelligence that have a higher value as it empowers a player to create unique in-game, off-chain assets that are highly playable and can greatly enhance that player’s chances of success in the game. Thus, an intelligence economy is created, where ownership of Bluepz prove to be extremely valuable and rewarding. This in turn, opens up multiple player journeys within the Beeznix gameverse, where a player might find it more profitable to become a dealer, selling special troops or weapons to other players at war with each other. What adds further to the value of Bluepz is its portability where it can be recognized and functional across multiple games or game modes.",
          "distribution_of_tokens": "Distribution of tokens",
          "distribution": "Distribution",
          "of_tokens": "of tokens",
          "chart": "Chart",
          "50ico": "50% ICO",
          "10marketing": "10% Marketing",
          "1bounty": "1% Bounty",
          "4community_service": "4% Community Service Reserve",
          "15strategies": "15% Strategic Partners",
          "20company": "20% Company Reserve",
          "use_of_proceeds": "Use of proceeds",
          "use": "Use",
          "of_proceeds": "of proceeds",
          "40giant": "40% GiantB (Logo)",
          "30marketing": "30% Marketing",
          "2gamerewards": "2% Game Rewards Bank",
          "10contingency": "10% Contingency",
          "18operations": "18% Operations & Game Development",
          "our_loadmap": "OUR ROADMAP",
          "april2018": "April 2018",
          "whitepaper_release": "Whitepaper Release",
          "may2018": "May 2018",
          "develop_erc20": "Develop ERC20 and ERC721 Platforms",
          "june2018": "June 2018",
          "ico_and_boarding": "ICO and Boarding of Farms",
          "august2018": "August 2018",
          "exchange_listing_and": "Exchange Listing and Game Development",
          "october2018": "October 2018",
          "game_demo": "Game Demo",
          "december2018": "December 2018",
          "beeznix_game_beta": "Beeznix Game Beta and Bluepz Airdrops",
          "january2019": "January 2019",
          "beeznix_game_release": "Beeznix Game Release",
          "february2019": "February 2019",
          "launch_of_goddess": "Launch of Goddess Honey",
          "februray2": "February",
          "farm_expansion_and": "Farm Expansion and Outreach",
          "march2019": "March 2019",
          "beeznix_expansion": "Beeznix Expansion",
          "apri2019": "April 2019",
          "begin_media_franchise": "Begin Media Franchise",
          "dont_miss_out": "Don't miss out, Stay updated",
          "enter_your_email": "Enter your email address",
          "copyright_2018": "Copyright © 2018 Bitney.io",
          "all_trademarks": "All trademarks and copyrights belong to their respective owners.",
          "login": "Log In",
          "signup": "Sign Up",
          "myaccount": "My Account",
          "logout": "Log Out",
          "buy": "Buy",
          "wallet": "Wallet",
          "history": "History",
          "tnxs": "Tnxs",
          "profile": "Profile",
          "ethereum_price_and": "Ethereum Price and BTNY Token Price",
          "volume_24h": "Volume 24h",
          "ethusd_price": "ETHUSD price",
          "token_price_in_usd": "BTNY Price in USD",
          "token_price_in_eth": "BTNY Price in ETH",
          "sign_to_ethereum_meta": "Sign to Ethereum network with",
          "you_can_connect": "You can connect your account using",
          "token_amount": "Token Amount",
          "sign_to_network_first": "Sign to network first.",
          "buy_tokens": "Buy Tokens",
          "sign_to_ethereum_priv": "Sign to Ethereum network with Private Key",
          "ethereum_price": "Ethereum Price",
          "gas_fee": "Gas Fee",
          "sign_to_ethereum_meta_priv": "Sign to Ethereum network with Metamask or Private Key",
          "btny_balance": "BTNY Balance",
          "withdraw_btny": "Withdraw BTNY",
          "wallet_address": "Wallet Address",
          "btny_amount": "BTNY Amount",
          "ethereum_balance": "Ethereum Balance",
          "withdraw_ethereum": "Withdraw Ethereum",
          "ethereum_amount": "Ethereum Amount",
          "transaction_history": "Transaction History",
          "btny_buy_history": "BTNY Buy History",
          "btny_transfer_history": "BTNY Transfer History",
          "you_have_no": "You have no transactions.",
          "ethereum_history": "Ethereum History",
          "kyc": "KYC Verification",
          "kyc_verification_status": "KYC verification status",
          "identify_card": "Identify Card verification",
          "proof_address": "Proof Address verification",
          "upload_id_card": "Upload ID card",
          "captured_image_id": "Captured image of Id card",
          "registered_users": "Registered Users",
          "user": "User",
          "user_email": "User Email",
          "email_verification": "Email Verification",
          "document_verification": "Document Verification",
          "address_verification": "Address Verification",
          "status": "Status",
          "full_name": "Full Name",
          "birthday": "Birthday",
          "country_phone_number": "Country Phone Number",
          "enter_phone_number": "Enter phone number",
          "card_number": "Card Number",
          "card_type": "Card Type",
          "issued_date": "Issued date",
          "upload": "Upload",
          "upload_document": "Upload Document",
          "captured_image_doc": "Captured image of Document",
          "billing_address": "Billing Address",
          "document_type": "Document Type",
          "set_erc721_addr": "Set ERC-721 Token's Smart-Contract Address",
          "owner_private_key": "Owner Private Key",
          "adress": "Address",
          "set": "SET",
          "more_info": "More Info",
          "not_provided": "Not Provided",
          "erc721_set_success": "ERC-721 Smart-Contract is set successfully!",
          "something_wrong_in_sm_setting": "Something wrong in Smart Contract setting!",
          "input_sm_priv_correct": "Please input Smart-Contract address and Private Key correctly...",
          "wait_confirmation_msg": "Please wait for the confirmation message. Usually Ethereum network takes time.",
          "something_wrong_user_verify": "Something wrong in User verification!",
          "verify": "Verify",
          "approve": "Approve",
          "reject": "Reject",
          "date_submit": "Date Submit",
          "date_birth": "Date of Birth",
          "country": "Country",
          "phone_number": "Phone Number",
          "card_number": "Card Number",
          "image_upload": "Image Upload",
          "full_address": "Full Address",
          "admin": "Admin",
          "or": "or",
          "my_wallet_address": "My Wallet Address",
          "withdraw": "Withdraw",
          "sign_ethereum_first": "Please sign to Ethereum network first!",
          "btny_transfer_success": "BTNY transferred successfully!",
          "btny_transfer_failed": "BTNY transfer failed!",
          "confirm": "Confirm",
          "cancel": "Cancel",
          "something_wrong_eth_trans": "Something wrong in Ethereum transfer!",
          "eth_transfer_success": "Ethereum transferred successfully!",
          "tnx_confirm_msg": "Please wait for the Transaction confirmation message.",
          "takes_time": "Usually Ethereum network takes time.",
          "input_your_privkey": "Please input your private key!",
          "bill_state": "Bill Statement",
          "bank_state": "Bank Statement",
          "other_state": "Other Fianance Document",
          "upload_success": "Successfully uploaded!",
          "something_wrong_document_upload": "Something wrong in document uploading.",
          "something_wrong_card_upload": "Something wrong in id card uploading.",
          "national_id": "National ID",
          "driving_lice": "Driving License",
          "passport": "Passport",
          "tnx_done_sucess": "Transaction done successfully!\nYou will receive an email for Verification Code.",
          "something_wrong_tnx": "Something wrong in Transaction!",
          "tokens_sold_private": "Tokens sold in Private Sale : ",
          "tokens_sold_pre1": "Tokens sold in Pre Sale1 : ",
          "tokens_sold_pre2": "Tokens sold in Pre Sale2 : ",
          "tokens_sold_public": "Tokens sold in Public Sale : ",

          "allanchan": "Allan Chan",
          "chairman": "Chairman & Advisor",
          "allanchan_detail": "With a seniority of 13 years in entrepreneurship, Allan brings a wave of knowledge in business. Bootstrapping businesses and driving them to success after success as seen with the multiple awards presented to BID international. With businesses tuned international and locally, Allan has maintain laudable business standards that presented his biotech company the honorable MSC status in Malaysia. Strong in business management, R&D, and product marketing, Allan builds strong cultures and strategies in business and delivers over-the-top sales volumes resulting in the multiple business set up all across Southeast Asia, Europe, Asia and Middle East. Allan currently is chairman of the advisor board to project Bitney, with his vast experience and successes in building businesses, Allan is set to bring great vision and solid business practices into project Bitney.",
          "desmondtan": "Desmond Tan",
          "partenring": "Partnering Business, Giant B",
          "desmondtan_detail": "Starting off in the timber industries to handling factory operations and eventually progressing into farming industry. Desmond ventured into business at a very young age and has much to do with the success in development, sustainability and vast expansion in the bee farm industry. An expert to this widespread in-demand global commodity, Desmond pioneers and champions R&D discoveries onto his very own bee farms. Be it understanding bee behavior, maximising honey output, creating the perfect farm environment, he’s the go-to industry expert. Spearheading business operations at Giant B over 10 years, Malaysia’s largest bee farm business with over 40 sub-divisions globally, Desmond brings a great deal to the table. With extensive beekeeping knowledge, F&B, strategic planning and business development, Desmond brings the secret of trades to support project Bitney. Currently partnering with Bitney to bring about cryptocurrency as in-game currency backed by honey farms, a first and only unique model for cryptocurrency, bee farms, blockchain, and game development.",
          "jeffereyng": "Jeffrey Ng", 
          "co_founder": "Co-Founder, Bitbubs Interactive",
          "jeffereyng_detail": "Jeff has served as Managing Director across industries such as retail and online distribution, and construction. With a strong entry in construction, Jeff has successfully build companies through product evangelism and setting industry standards by delivering quality assurance to match customer expectations. With success following suit, Jeff ventured into retail and online distribution bring his wealth of knowledge and experience in quality assurance and delivery. Currently praying a role with project Bitney to oversee and ensure delivery of products and services are in line with regulations and market standards.",
          "chngjunwei": "Ch’ng Jun Wei",
          "ceofofounder": "CEO & Co-Founder, Bitbubs Interactive",
          "chngjunwei_detail": "Equipped with strong product knowledge and the experience of setting up multiple companies across various industries including publishing, F&B and technology (mobile apps), Jun Wei has hands on knowledge of building strong foundations of a company. With experiences of managing large teams to startups sizes, Jun Wei has set foot in entrepreneurship in his early days. In his earlier years of entrepreneurship, Jun Wei has an eye for assembling the right core team to build projects, set out visions and mission of businesses and deliver exemplary business operation standards. Being no stranger to both blockchain and cryptocurrency respectively, Jun Wei has spent 3 years fully focusing his attention to blockchain technology understanding the complexity of the highly secured decentralized platform. Previously strong armed with mobile applications development and publishing, this created a gateway into the media & entertainment market which he recognized and pointed out as the next emerging economy market. With an appetite and a positive advocate of cryptocurrency and blockchain, he has participated in various ICOs and now spearheads project Bitney’s mission into bringing cryptocurrency into games. Equipped with the history of mobile application publication, Bitney is set to launch its very first unique game that will adopt cross-industry functions on mobile platform.",
          "limyaohan": "Lim Yao-Han", 
          "coo": "COO & Co-Founder, Bitbubs Interactive",
          "limyaohan_detail": "A graduate of Industrial Design and highly creative individual with diverse background and extensive knowledge in various fields such as marketing, creative designs, education, blockchain and most recently, games. Yao-Han build a solid start in career with the advantage of having multiple skill set including product design & development marketing, advertising, and multiple software skills. He has taken on roles in business relationship management to build companies and establish new developments; an experienced educator when he served in teaching & training as a lecturer in Han Chiang College. Subject expert on Multimedia, Design Illustration, Marketing and Computer Game Design. In his capacity, Yao-Han was Head of Creative in a fintech space, handling creative direction control and building ideas, and business development strategies within the start-up space. This grew his knowledge and expertise for the start-up environment and developed solid knowledge of business strategies. Passionate in start-ups & entrepreneurship, Yao-Han has spent years being in multiple industries where he spearheaded innovative ideas.",
          "jianina": "Jia nina", 
          "marketing_director": "Marketing Director, Bitbubs Interactive",
          "jianina_detail": "A former legal eagle who graduated from Northumbria University (UK). Jia kicked off her career in Corporate Banking in early days of legal practice with reputable clients such as OCBC bank and RHB bank respectively. Seasoned in Corporate Communications, PR, marketing, and business development with up to 7 years of experience. Her notable publishing works can be traced back since her days in lifestyle publication magazines as such – Top10 of Asia, Top 10 of Malaysia with circulations up to 500,000 copies worldwide. Jia fast-tracked her career development as Streamline Studios’ PR & Communications lead, a global leading game developers with celebrated titles such as FFXV, SF5, Gears of War and more. Skilled in evangelism, Jia has extensive experience in business presentations, developing meaningful relationships with top industry players & influencers such as VC investors, top game producers and government affiliates such as MDEC (Malaysia). A master of craft of 7years, Jia spearheaded the Marketing & Communications division in a fintech company, on the use of the blockchain technology. Jia currently leads the Marketing & Communications with Bitbubs Interactive & Bitney Pte Ltd, creating a universal voice and brand identity in games and technologies respectively.",
          "guptaraghava": "Gupta Raghava", 
          "leaddev": "Lead Developer",
          "guptaraghava_detail": "Gupta has 7 years experience in technology as a developer. An experienced software engineer with a demonstrated history in the information technology and services industry. Working with global renown businesses such as Salesforce, Gupta is highly skilled in Rest API, visualforce pages, jQuery, PHP, ORACLE SQL and MYSQL. A strong engineering professional focused in Computer Science with highly developed set skills and experience with blockchain. Gupta’s passion in the blockchain sphere paved the way as lead developer to support with the developments of ERC 20, a technical standard used for smart contracts on the Ethereum blockchain for token implementations.",
          "nizamrahman": "Nizam Rahman",
          "leaddsng": "Lead Designer",
          "nizamrahman_detail": "A highly creative individual with 5 years experience in lead creative roles, Nizam has worked for media corporate giants such as Astro, handling subsidiary divisions supporting live videos and video assets designs. Highly skilled in designing brands, concepts, advertisements, website and much more. Nizam brings concepts into live through a creative lens and has helped many corporate brands establish their identities in the markets. Nizam’s venture into the blockchain industry began in early 2016 and now supports creative works with project Bitney. An avid gamer, cryptocurrency trader and artistic personality, Nizam spends a great deal of time within the art community and contributes creative knowledge and impact within the company.",
          "louisewong": "Louise Wong",
          "seniormarketing": "Senior Marketing Executive",
          "louisewong_detail": "With over 15 years of working experience in marketing and branding, Louise has successfully supported businesses in marketing initiatives to establish presence in the consumer market. From marketing health supplements to online retail, Louise has the know- how in marketing. Leading several key marketing positions and maintaining portfolios in social media marketing, event planning & management, designing marketing campaigns, content marketing and much more. Louise actively leads marketing initiatives in project Bitney to ensure consumer engagement is achieved and the brand messages is accurately crafted for the intended audience.",
          "darian": "Darian",
          "cto": "CTO",
          "darian_detail": "A certified bachelor of engineering with deep-rooted knowledge and experience in blockchain, cryptocurrency and games, Darian has held key positions in various companies but particularly focused on technology. Specialized expertise in blockchain, CSS, JavaScript, Ruby, PHP, Python, third party APIs, DB and Server and project management tools. Darian’s recent endeavor includes dabbling into virtual reality technology, website development and real time server development. With 10 years experience in multiple organizations as lead developer and CTO, Darian’s deep understanding for technology and softwares is key to implementing and developing a successful and sustainable project in b2b and b2c markets respectively. Darian brings innovation solutions in the complex developments of project Bitney as CTO. With his latest quest to build ERC 721 tokens, a free open standard that creates unique tokens that will serve as an interesting feature in Beeznix the game.",
          "darrenkiang": "Darren Kiang",
          "advisor": "Advisor",
          "darrenkiang_detail": "Highly skilled in finance and personal development, Darren’s vast knowledge as financial mediator and angel investments has been seen in the various successful projects undertaken. An experienced business & finance advisor, Darren has integrated over 20 years resources worth into businesses providing solution platforms such as branding, sales and marketing, business model designs and cooperation with financial institutions on capital integration, project funding and structuring of financial products. Darren’s positive personality is a direct result of vast self-development and sales success experiences paired with a history in creative designs. Serving as advisor to project Bitney, Darren will support the financial evaluation, project funding and scaling of financial products and services to bring a successful project to life while adding creative input to the game development process.",
          "joeong": "Joe Ong",
          "gamedsng": "Game Designer",
          "joeong_detail": "Skilled in various roles from key account management, business development, partnership and marketing, and product deck designs. Joe has worked on multiple successful projects for a wide range of companies. With a lifelong passion for games and a part-time marketing wizard, he has extensive experience with organically marketing android apps (with one project making a hit with 7 million downloads using marketing spend of USD 100 only). Joe’s latest projects are fintech related and most recently joined project Bitney as lead game designer handling game concepts and game-plays. Joe’s track record of success with android app marketing and passion for delivering creative concepts via presentations puts the Bitney team on track with a huge advantage. Beeznix the game is set to launch strong on the mobile market platform.",
          "tekucheong": "Teku Cheong",
          "2dart": "2D Artist",
          "tekucheong_detail": "Skilled in illustration in the entertainment design scene, Teku is passionately strong in concept art, storyboards and matte painting. The developed passion for art early in his early day sparked interest and the pursuit in creative designs - particularly in creating aesthetic designs with an eccentric style. Equipped with the keen eye for detail and functionality, Teku designs meticulously and creates concepts out of the box. Some notable work include creating visuals and concepts for IPs such as characters, environments and props, creating storyboards for character animations, designing UI layouts for apps, creating textures for modellers, conceptualising and proposing gameplay mechanics in company projects."
        }
      },
      ch: {
        translations: {
          "the_value": "价值",
          "partners": "合作伙伴",
          "the_game": "游戏",
          "token_sale": "代币销售",
          "roadmap": "路线图",
          "team": "团队",
          "contact": "联系",
          "game": "游戏",
          "token": "代币",
          "crypto_game_rewards": "由真正的蜂蜜农场提供支持的区块链移动游戏奖励",
          "play_and_earn": "通过游戏而赚取实际价值的奖励！",
          "read_whitepaper": "阅读白皮书",
          "a_unique_bus": "一项独特的游戏奖励",
          "for_game_rewards": "商业模式",
          "btny_built_off": "Bitney是在一个既定的创收蜂蜜业务之上而建立的。 以所获取的蜂蜜销售利润用于从交易所购买Bitney代币。 从此回购中，20％的代币将被销毁，而其中的80％将被重新存入Beeznix 游戏奖金银行。这个循环从而保障了Bitney的价值。",
          "coming_soon": "即将到来",
          "game_trailer": "游戏预告片",
          "more_honey": "更多蜂蜜，更多奖励",
          "corss_industry": "一个跨行业的合作企业，使用移动游戏 来加速世界各地中小型蜂蜜农场的规模化。",
          "bithubs_interactive": "BITBUBS 互动团队与“蜜蜂共和国”（一项蜂农倡议），创造了一个独特的生态系统，将移动游戏多元宇宙中获得的收入用于扩张蜂蜜农场。相反，农场的收入也用于游戏扩展，因为两者都在以高速扩展。",
          "out_partners": "我们的合作伙伴",
          "beeznix_heists": "BEEZNIX: 蜂蜜盗取游戏",
          "a_massively_multi": '这是一个以以基地建设者行动/战略参与的大型多玩家平台，采用ERC721非可替代代币（NFT）作为“蓝图”而创建的知识经济，让玩家通过真正的拥有权将其游戏资产货币化。',
          "based_on_a_story": "这款游戏是根据一部小说创造的。小说讲述的是一个8岁的孤儿在一家玩具熊工厂做童工的经历。游戏将这个孩子的精彩世界搬上了色彩纷呈的屏幕，并为他的悲惨生活设计了应对机制。以这个内心充满爱和恐惧的孩子为原型，我们设计了一个平行宇宙。他日常生活中的一切也被转译成了一个“蜂蜜宇宙”，对入门游戏模式（Beeznix大型多人即时战略游戏）中的玩家来说，“蜂蜜宇宙”中的以下元素极大地丰富了游戏的可玩性和真正的奖赏：",
          "build_your_base": "建立你的基地以保护您的蜂巢",
          "collect_character_blueprints": "收集角色蓝图以生产防御单元",
          "visit_other_players": "到访其他玩家的基地并偷取他们的蜂蜜",
          "sell_your_honey": "出售您的蜂蜜以换取Bitney",
          "sell_your_blueprints": "出售您的蓝图单元以换取Bitney",
          "creating_an_intell": "创造一种知识经济",
          "the_bluepz_concept": "Bluepz 这一概念得以让游戏玩家将自己的游戏内“知识产权”货币化，为游戏开辟了一个新的维度。与皮肤相比，Bluepz 被认为是更具价值的知识，因为它可以让玩家创造独特的游戏内链下资产。这些资产可玩性高，并且可极大提升玩家在游戏中的成功几率。因此，当 Bluepz 的所有权变得极具价值和利润，知识经济便产生了。这进而又为 Beeznix 游戏玩家创造更多的选择，玩家可能会成为经销商，向其他处于竞争关系的玩家出售特种部队或武器，因为他们发现这更加赚钱。Bluepz的另一大优点在于它的可移性，它可以被不同的游戏或游戏模式认可从而发挥作用。",
          "distribution_of_tokens": "代币发放",
          "distribution": "发放",
          "of_tokens": "代币",
          "chart": "图表",
          "50ico": "50% ICO",
          "10marketing": "10%市场营销",
          "1bounty": "1%赏金",
          "4community_service": "4％社区服务储备",
          "15strategies": "15％战略合作伙伴",
          "20company": "20％公司储备金",
          "use_of_proceeds": "资金分配",
          "use": "资金",
          "of_proceeds": "分配",
          "40giant": "40% GiantB (Logo)",
          "30marketing": "30% 市场营销",
          "2gamerewards": "2％ 游戏奖金银行",
          "10contingency": "10% 应变储备钱包",
          "18operations": "18% 营运与游戏开发",
          "our_loadmap": "我们的路线图",
          "april2018": "2018年4月",
          "whitepaper_release": "白皮书发布",
          "may2018": "2018年5月",
          "develop_erc20": "开发ERC20和ERC721平台",
          "june2018": "2018年6月",
          "ico_and_boarding": "首次代币发行与蜂场巡视",
          "august2018": "2018年8月",
          "exchange_listing_and": "交易所上市和游戏开发",
          "october2018": "2018年10月",
          "game_demo": "游戏示范",
          "december2018": "2018年12月",
          "beeznix_game_beta": "Beeznix 游戏 Beta测试与 Bluepz 加密游戏资产空投测试",
          "january2019": "2019年1月",
          "beeznix_game_release": "Beeznix 游戏发布",
          "february2019": "2019年2月",
          "launch_of_goddess": "推出女神蜂蜜",
          "februray2": "2月",
          "farm_expansion_and": "农场扩建和外展",
          "march2019": "2019年3月",
          "beeznix_expansion": "Beeznix扩展",
          "apri2019": "2019年4月",
          "begin_media_franchise": "开始媒体特许经营",
          "dont_miss_out": "切勿错过，敬请密切关注",
          "enter_your_email": "输入您的电子邮箱地址",
          "copyright_2018": "版权所有©2018 Bitney.io",
          "all_trademarks": "所有的商标和版权都属于其各自所有者。",
          "login": "登录",
          "signup": "注册",
          "myaccount": "我的账号",
          "logout": "登出",
          "buy": "购买",
          "wallet": "钱包",
          "history": "过往记录",
          "tnxs": "交易",
          "profile": "个人资料",
          "ethereum_price_and": "以太币价格与BTNY代币价格",
          "volume_24h": "24小时交易量",
          "ethusd_price": "以太币美元价格",
          "token_price_in_usd": "代币价格（美元)",
          "token_price_in_eth": "代币价格（以太币）",
          "sign_to_ethereum_meta": "以Metamask登录 ",
          "you_can_connect": "您可以使用Metamask连接您的帐户",
          "token_amount": "代币数量",
          "sign_to_network_first": "先登录网络",
          "buy_tokens": "购买代币",
          "sign_to_ethereum_priv": "使用私钥密码登录以太坊网络 ",
          "ethereum_price": "以太坊货币价格",
          "gas_fee": "Gas费用",
          "sign_to_ethereum_meta_priv": "使用以太坊钱包账号或私人密码登录以太坊网络",
          "btny_balance": "BTNY余额",
          "withdraw_btny": "BTNY提款",
          "wallet_address": "电子钱包网址",
          "btny_amount": "BTNY数量",
          "ethereum_balance": "以太币余额",
          "withdraw_ethereum": "以太币提款",
          "ethereum_amount": "以太币价格",
          "transaction_history": "交易过往记录",
          "btny_buy_history": "BTNY 购买过往记录",
          "btny_transfer_history": "BTNY 转账过往记录",
          "you_have_no": "您并无任何交易。",
          "ethereum_history": "以太币过往记录",
          "kyc": "KYC了解您的客户",
          "kyc_verification_status": "KYC验证状态",
          "identify_card": "身份证验证",
          "proof_address": "地址验证证明",
          "upload_id_card": "上载身份证",
          "captured_image_id": "拍摄身份证图片",
          "registered_users": "注册用户",
          "user": "用户",
          "user_email": "用户电子邮件",
          "email_verification": "电子邮件验证",
          "document_verification": "文件验证",
          "address_verification": "地址验证",
          "status": "状态",
          "full_name": "全名",
          "birthday": "生日",
          "country_phone_number": "电话号码国家代码",
          "enter_phone_number": "输入电话号码",
          "card_number": "卡号码",
          "card_type": "卡类型",
          "issued_date": "发行日期",
          "upload": "上载",
          "upload_document": "上载文件",
          "captured_image_doc": "拍摄文件图片",
          "billing_address": "帐单地址",
          "document_type": "文件类型",
          "set_erc721_addr": "设置ERC-721智能合同地址",
          "owner_private_key": "所有者私钥",
          "address": "地址",
          "set": "设置",
          "more_info": "更多信息",
          "not_provided": "不提供",
          "erc721_set_success": "ERC-721智能合同成功设置！",
          "something_wrong_in_sm_setting": "智能合同设置有问题！",
          "input_sm_priv_correct": "请正确输入智能合约地址和私钥...",
          "wait_confirmation_msg": "请等待确认消息。 通常以太坊网络需要时间。",
          "something_wrong_user_verify": "用户验证有问题！",
          "verify": "校验",
          "approve": "批准",
          "reject": "拒绝",
          "date_submit": "提交日期",
          "date_birth": "生日",
          "country": "国家",
          "phone_number": "电话号码",
          "card_number": "卡号",
          "image_upload": "图片上传",
          "full_address": "完整地址",
          "admin": "管理员",
          "or": "要么",
          "my_wallet_address": "我的钱包地址",
          "witdhraw": "提款",
          "sign_ethereum_first": "请先登录以太坊网络！",
          "btny_transfer_success": "BTNY成功转移！",
          "btny_transfer_failed": "BTNY转移失败！",
          "confirm": "确认",
          "cancel": "取消",
          "something_wrong_eth_trans": "以太坊转移出了点问题！",
          "eth_transfer_success": "以太坊成功转移！",
          "tnx_confirm_msg": "请等待确认消息。",
          "takes_time": "通常以太坊网络需要时间。",
          "input_your_privkey": "请输入您的私钥！",
          "bill_state": "比尔声明",
          "bank_state": "银行对帐单",
          "other_state": "其他财务文件",
          "upload_success": "成功上传！",
          "something_wrong_document_upload": "文档上传有问题。",
          "something_wrong_card_upload": "身份证上传有问题。",
          "tnx_done_sucess": "交易成功完成！\n您将收到验证码的电子邮件。",
          "something_wrong_tnx": "交易出错了！",
          "tokens_sold_private": "代币在私人出售中出售 : ",
          "tokens_sold_pre1": "代币在Pre Sale1 : ",
          "tokens_sold_pre2": "代币在Pre Sale2 : ",
          "tokens_sold_public": "公开出售的代币 : ",

          "allanchan": "Allan Chan",
          "chairman": "主席兼顾问",
          "allanchan_detail": "Allan 拥有 13 年的创业资历，为商业带来了知识浪潮。 通过向 BID 国际提供的多个奖 项，成功引导企业并推动它们取得成功。随着国际和本地业务的调整，Allan 保持了值 得赞扬的商业标准，这使他的生物技术公司在马来西亚获得了 MSC 状态的荣誉。 Allan 在业务管理，研发和产品营销方面具有很强的实力，进而在业务方面建立了强大 的文化和战略，并提供了顶尖的销售量，从而在东南亚，欧洲，亚洲和中东建立了多 种业务。Allan 目前担任 Bitney 项目顾问委员会主席，凭借他在建立业务方面的丰富经 验和成功经验，Allan 将为 Bitney 项目带来卓越的愿景和扎实的商业实践。",
          "desmondtan": "Desmond Tan",
          "partenring": "业务合作伙伴, Giant B",
          "desmondtan_detail": "从木材行业开始，到工厂运营，最终进入农业。Desmond 在很小的时候就开始从事商 业活动，这与蜂农业的发展，可持续性和大规模扩张有很大关系。Desmond 擅解于广 泛需求的全球商品，他把研发成果开拓并捍卫于自己的养蜂场。无论是了解蜜蜂行 为，最大限度地提高蜂蜜产量，创造完美的农场环境，他都是行业专家。作为马来西 亚最大的蜂场业务，在全球拥有超过 40 个子部门的 Giant B 业务运营超过 10 年， Desmond 拥有着许多优势。凭借广泛的养蜂知识，餐饮，战略规划和业务发展， Desmond 抱持着交易秘诀，以支持 Bitney 项目。目前与 Bitney 合作将加密货币作为游 戏货币，由蜂蜜农场支持，成为加密货币，养蜂场，区块链和游戏开发的第一个也是 唯一一个独特的模式。",
          "jeffereyng": "Jeffrey Ng", 
          "co_founder": "联合创始人, Bitbubs Interactive",
          "jeffereyng_detail": "Jeff 曾担任零售和在线分销以及建筑等行业的总经理。凭借强大的建筑条件，Jeff 通过 产品传播和制定行业标准成功地建立了公司，提供了符合客户期望的质量保证。追随 着成功趋势，Jeff 进入零售和在线分销领域，在质量保证和交付方面积累了丰富的知 识和经验。 目前，负责监督并确保 Bitney 项目产品和服务的交付符合法规和市场标 准。",
          "chngjunwei": "Ch’ng Jun Wei",
          "ceofofounder": "总裁&联合创办人, Bitbubs Interactive",
          "chngjunwei_detail": "Jun Wei 拥有强大的产品知识和在各个行业(包括出版，餐饮和技术(移动应用程 序))建立多家公司的经验，他掌握了建立公司强大基础的知识。凭借管理大型团队 创业规模的经验，Jun Wei 早年就开始涉足创业。在他早年的创业历程中，Jun Wei 着 眼于组建合适的核心团队来建立项目，设定企业的愿景和使命，并提供典型的业务运 营标准。Jun Wei 分别对区块链和加密货币并不陌生，他花了 3 年时间将注意力集中在 区块链技术上，以了解高度安全的分散式平台的复杂性。此前，凭借移动应用程序的 开发和发布，创造了一个进入媒体和娱乐市场的门槛，他认识并指出这是下一个新兴 经济体市场。凭借对加密货币和区块链的积极倡导与求知欲，他参与了各种 ICO，如 今率先计划 Bitney 将加密货币纳入游戏的使命。 凭借移动应用程序发布的历史， Bitney 将推出其首款在移动平台上采用跨行业功能的独特游戏。",
          "limyaohan": "Lim Yao-Han", 
          "coo": "首席运营&联合创始人, Bitbubs Interactive",
          "limyaohan_detail": "毕业于工业设计和拥有高度创造性，在市场，创意设计，教育，区块链和最近的游戏 等各个领域具有不同的背景和广泛的知识。Yao-Han 拥有多项技能，包括产品设计和 开发营销，广告和多种软件技能，从而在职业生涯中树立了良好的开端。他曾从事商 业关系管理方面，负责建立公司并建立新的发展; 在汉江学院担任讲师教学和培训时， 他是一位经验丰富的教育工作者。同时也善于多媒体，设计插图，市场营销和计算机 游戏设计专题。Yao-Han 曾是金融科技领域的创意总监，在创业领域处理创意方向控 制和构思以及业务发展战略。这增强了他在创业环境方面的专业知识，并培养了对商 业战略的扎实知识。 Yao-Han 热衷于初创企业和企业家精神，多年来一直在多个行业 中领导创新理念。",
          "jianina": "Jia nina", 
          "marketing_director": "市场总监, Bitbubs Interactive",
          "jianina_detail": "从诺桑比亚大学(英国)毕业的前法老鹰。 Jia 分别在华侨银行和 RHB 银行等知名客 户的法律业务初期开始了她的企业银行业务。 在企业传播，公关，营销和业务发展方 面经验丰富，拥有长达 7 年的经验。她着名的出版作品可以追溯到她在生活方式出版 杂志上的日子，比如 - 亚洲十大，马来西亚十大，全球发行量高达 50 万份。作为 Streamline Studios 的公关和传播主管，全球领先的游戏开发商，拥有着名的游戏，如 FFXV，SF5，战争机器等等，Jia 快速追踪她的职业发展。Jia 擅长传福音，在商业演 讲方面拥有丰富的经验，与风险投资者，顶级游戏制作人和 MDEC(马来西亚)等政 府附属机构等顶级行业参与者和影响者建立了有意义的关系。作为一位拥有 7 年历史 的工艺大师，Jia 使用区块链技术领导了金融科技公司的营销与传播部门。Jia 目前在 Bitbubs Interactive&Bitney Pte Ltd 担任营销和传播负责人，分别在游戏和技术领域创造 了通用语音和品牌标识。",
          "guptaraghava": "Gupta Raghava", 
          "leaddev": "首席开发人员",
          "guptaraghava_detail": "Gupta 作为开发人员拥有着 7 年的技术经验。 经验丰富的软件工程师，在信息技术和 服务行业拥有丰富的经验。 通过与 Salesforce 等全球知名企业合作，Gupta 在 Rest API，visualforce 页面，jQuery，PHP，ORACLE SQL 和 MYSQL 方面具有高超的技能。 一个强大的工程专业人员，专注于计算机科学，拥有高度发达的技能和区块链经验。 Gupta 对区块链领域的热情为首席开发人员铺平了道路，以支持 ERC 20 的发展，ERC 20 是用于以太网区块链智能合约的技术标准，用于代币实施。",
          "nizamrahman": "Nizam Rahman",
          "leaddsng": "首席设计师",
          "nizamrahman_detail": "Nizam 是一位在创意设计领导上拥有 5 年经验的重要角色，曾在 Astro 等媒体企业巨 头工作，同时在其子公司负责处理支持实时视频和视频资产设计。 在设计品牌，概 念，广告，网站等方面具有高超的技能。 Nizam 通过创意镜头将概念带入现场，并帮 助许多企业在市场中建立自己的品牌。 Nizam 在 2016 年初开始进入区块链行业，目 前在支持 Bitney 项目中的创意作品。 作为狂热的游戏玩家，加密货币交易者和艺术个性，Nizam 在艺术社区中花费了大量时间，并在公司内部提供不少创作方面的知识与 其在相关市场上影响力。",
          "louisewong": "Louise Wong",
          "seniormarketing": "高级营销主管",
          "louisewong_detail": "Louise 在市场营销和品牌推广方面拥有超过 15 年的工作经验，已成功支持企业在营 销活动中建立在消费者市场的地位。 从营销健康补品到在线零售，Louise 拥有营销方 面的专业知识。 领导多个关键营销职位，并在社交媒体营销，活动策划和管理，设计 营销活动，内容营销等方面保持投资组合。 Louise 积极领导 Bitney 项目的营销活 动，以确保实现消费者参与，并为目标受众准确地制作品牌信息。",
          "darian": "Darian",
          "cto": "首席技术总监 CTO",
          "darian_detail": "Darian 是一名受认证的工程学士，在区块链，加密货币和游戏方面拥有深厚的知识和 经验，曾在多家公司担任重要职位，但特别注重技术。区块链，CSS，JavaScript， Ruby，PHP，Python，第三方 API，数据库和服务器以及项目管理工具方面的专业知 识。 Darian 最近参与的项目包括涉足虚拟现实技术，网站开发和实时服务器开发。作 为首席技术开发人员与首席技术总监，多年来已在多个相关组织建立了 10 年经验， Darian 对技术和软件的深刻理解是分别在 b2b 和 b2c 市场实施和开发成功和可持续项 目的关键。作为首席技术总监， Darian 为 Bitney 项目的复杂开发提供创新解决方案。 他最近开始构建 ERC 721 代币，采用一个自由开放标准创建最独特的代币，以作为 Beeznix 游戏中一个相当有趣的优势。",
          "darrenkiang": "Darren Kiang",
          "advisor": "顾问",
          "darrenkiang_detail": "Darren 的能力优势在于金融和个人发展领域，在各种成功的项目中都可以看到他对金 融危机调解和运作天使投资方面的丰富知识。 Darren 是一位经验丰富的商业和财务顾 问，已将超过 20 年的资源整合到企业中，提供解决方案平台，如品牌，销售和营销， 商业模式设计以及与金融机构在资本整合，项目融资和金融产品结构方面的合作。 Darren 的积极人格与其创意设计背景已促成他过往许多在营销方面的成功案例。 作为 Bitney 项目的顾问，Darren 将支持金融产品和服务的财务评估，项目融资和扩展，以 便在为游戏开发过程添加创意输入的同时将成功的项目变为现实。",
          "joeong": "Joe Ong",
          "gamedsng": "游戏设计师",
          "joeong_detail": "擅于掌握关键客户管理，业务开发，合作伙伴关系和营销以及产品组合设计等各种职 责。 Joe 曾为多家公司参与过多个成功的项目。 凭借对游戏和兼职营销向导的热诚， 他在有机营销 Android 应用程序方面拥有丰富的经验(其中一个项目仅使用 100 美元 的营销支出就获得了 700 万次下载)。 Joe 的最新项目与金融科技(fintech)相关， 最近加入项目 Bitney 作为主要游戏设计师处理游戏概念和游戏。 Joe 在安卓 (Android)应用营销方面的成功记录以及通过演示提供创意概念的热诚信使得 Bitney 团队走上了巨大的优势。 Beeznix 的游戏将在移动市场平台上强势推出。",
          "tekucheong": "Teku Cheong",
          "2dart": "2D 概念设计师",
          "tekucheong_detail": "擅于设计动画领域里的插图，Teku 在概念设计，故事板创作和哑光绘画方面充满热 情。 早期对艺术的热枕激发了他对创意设计的兴趣和追求 - 特别是在创造具有古怪风 格的美学设计方面。 Teku 配备了对细节和功能的敏锐洞察力，精心设计并创造出开 箱即用的概念。 一些值得注意的工作包括创建 IP 的视觉和概念，如角色，环境和道 具，为角色动画创建故事板，为应用程序设计 UI 布局，为建模者创建纹理，概念化和 提出公司项目中的游戏机制。"
        }
      }
    },
    fallbackLng: 'en',

    // have a common namespace used around the full app
    ns: ['translations'],
    defaultNS: 'translations',

    keySeparator: false, // we use content as keys

    interpolation: {
      escapeValue: false, // not needed for react!!
      formatSeparator: ','
    },

    react: {
      wait: true
    }
  });

export default i18n;
